### ISSUE TITLE
types used for the color field in Elements.js is not consistent

### ISSUE THREAD

**Issue by jbphet** [phetsims/nitroglycerin#8]
For the various static elements, most colors are strings, but at least one - oxygen - is a Color object.  This just bit me while doing some integration.  It would probably be better if the types were consistent.

**Comment by pixelzoom** [comment]
@jbphet Sounds like you're writing code that relies on {Color} or {string}.  I always support both types, because they are both supported by scenery.  And I think that a common-code library like nitroglycerin should be able to use either type.  So my recommendation is to fix the client code rather than limit the common-code library.

**Comment by pixelzoom** [comment]
Looking at Element.js .... The Color in question is scenery-phet.PhetColorScheme.RED_COLORBLIND.  So I feel even more strongly about what I said above.  PhetColorScheme shouldn't be restricted to using {string} or {Color} for colors, they are both valid color types.

**Comment by jbphet** [comment]
I've made the code in States of Matter able to handle either type for color specs.  Closing.
